### ISSUE TITLE
Middleman Failing to Update browser since Yosemite 10.10.2 and command line Tools update

### ISSUE THREAD

**Issue by trejster** [middleman/middleman#1484]
I'm having real problems since upgrading to latest version of Yosemite plus the latest version of command line tools. Basically none of my changes are getting output to the browser even when I refresh the browser. I have to restart middleman to see any changes, can anyone help please?

**Comment by tdreyno** [comment]
Reboot?

**Comment by trejster** [comment]
First thing I tried ;) The only option that does work for me is using middleman --force-polling --verbose - that forces the browser to reload after about 5 seconds. Without that command I get no refresh, even a manual refresh of the browser doesnt show the changes

**Comment by tdreyno** [comment]
Maybe you need to re-compile some of the `listen` gem. Are you using RVM or using anything where you could get a clean Ruby gem state?

**Comment by trejster** [comment]
Hi, tbh Im completely new to Ruby so youll have to bear with me. Im running ruby 1.9.3 at the moment - not using RVM do you think I should do so? Does middleman require a specific version

Note - I have now also updated middleman to the latest version, issue still occuring

**Comment by trejster** [comment]
FYI Im getting an issue on windows also - I get the following:

== The middleman is loading

Then it immediately stops and returns to the command prompt

**Comment by trejster** [comment]
So currently trying to get this working on windows. I installed 'pik' to allow me to use a clean version of ruby. Im running ruby 2.2.
When running bundle install after running middleman I get the following error:

'An error occured while installing eventmachine <1.0.7>.. see image attached
![image](https://cloud.githubusercontent.com/assets/5671026/6687161/f8414b46-cc9f-11e4-9dc0-8362ba22a8a5.png)

**Comment by trejster** [comment]
Now ive gone back to ruby 1.9.3 and back to middleman version 3.3.7. On windows I now get this error. I've lost a lot of dev time to this now, cant get it working on windows or the mac, im all out of ideas

![image](https://cloud.githubusercontent.com/assets/5671026/6687706/3e3206cc-cca5-11e4-8100-3cedcb7f1677.png)

**Comment by tdreyno** [comment]
Looks like your compiler is messed up on that windows install.

As far as Mac, I'm on the exact same platform and version and not having those issues :(

We just fixed an error in `middleman-sprockets`, can you try adding the following to your Gemfile on a the compiling copy (OS X).

```
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets'
```

Also, are you using RVM or the built-in OS X version of Ruby

**Comment by trejster** [comment]
Hi. Windows still failing - gone back to Mac for the time being (I develop on both).

So ive installed rvm with ruby 1.9.3. Latest version of middleman plus the fix that you mentioned - still not getting any changes output to the browser?

**Comment by trejster** [comment]
Ah this is a nightmare. Ive now tried installing latest version of middleman and ruby 2.2.1 via RVM. Latest  issue is now this:

NoMethodError: undefined method `encoding' for nil:NilClass
	/Volumes/ExtHD-Mac/users/gareth/.rvm/gems/ruby-2.2.1/gems/temple-0.7.5/lib/temple/filters/remove_bom.rb:8:in `call'

**Comment by trejster** [comment]
BTW I also tried removing and installing middleman, creating a new project with the blog switch. Then running middleman build --verbose. I get a similar error: 
undefined method `force_encoding' for nil:NilClass

Please help, im now falling behind on an urgent project :(

**Comment by tdreyno** [comment]
Sorry, @trejster, I suggest you move on to another solution. There isn't enough here for me to debug your specific system, but, if this were a widespread issue, I'd be drowning in bug reports today. I'm using the same setup locally, as are most of my devs without issue.

I suggest trying a fresh machine to see if it is reproducible.

**Comment by trejster** [comment]
Ok thanks for looking into it for me

**Comment by scottkellum** [comment]
I just upgraded to Yosemite and am running into the same issue. Still working to identify what is causing the problem.

**Comment by scottkellum** [comment]
Having trouble finding the problem, testing old repos I know worked, trying new repos with rbenv and different ruby versions, trying the system version of ruby, turning my machine off and on again.

No errors appear in the console.

**Comment by tdreyno** [comment]
@scottkellum You're having the compile error or the `force_encoding` error?

**Comment by scottkellum** [comment]
@tdreyno This relates to the original issue posted (sorry, this thread is very divergent)

I need to restart middleman in the terminal in order to see changes to my sites after upgrading to Yosemite. This effects all files, markup, styles and JS. No errors occur in the console but I need to stop middleman and start it again to see changes.

**Comment by tdreyno** [comment]
@scottkellum `Gemfile.lock` please?

**Comment by tdreyno** [comment]
I suspect this bug is somewhere in `listen` and they've been having lots of stability issues :(

**Comment by scottkellum** [comment]
Fortunately it’s not a mission chritical project. Here is the `Gemfile.lock`. Thanks for looking into this! :smile: 

```yml
GEM
  remote: http://rubygems.org/
  specs:
    activesupport (4.1.10)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    chunky_png (1.3.4)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    color-schemer (0.2.8)
      compass-blend-modes (~> 0.0.2)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-blend-modes (0.0.2)
      compass
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.0.7)
    execjs (2.5.2)
    exifr (1.2.2)
    ffi (1.9.8)
    fspath (2.1.1)
    haml (4.0.6)
      tilt
    hike (1.2.3)
    hitimes (1.2.2)
    hooks (0.4.0)
      uber (~> 0.0.4)
    htmlcompressor (0.1.2)
    http_parser.rb (0.6.0)
    i18n (0.6.11)
    image_optim (0.20.2)
      exifr (~> 1.1, >= 1.1.3)
      fspath (~> 2.1)
      image_size (~> 1.3)
      in_threads (~> 1.3)
      progress (~> 3.0, >= 3.0.1)
    image_optim_pack (0.2.1.20150422)
      fspath (~> 2.1)
      image_optim (~> 0.19)
    image_size (1.4.1)
    in_threads (1.3.1)
    json (1.8.2)
    kramdown (1.7.0)
    listen (2.10.0)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    middleman (3.3.7)
      coffee-script (~> 2.2)
      compass (>= 1.0.0, < 2.0.0)
      compass-import-once (= 1.0.5)
      execjs (~> 2.0)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-core (= 3.3.7)
      middleman-sprockets (>= 3.1.2)
      sass (>= 3.4.0, < 4.0)
      uglifier (~> 2.5)
    middleman-blog (3.6.0.beta.2)
      addressable (~> 2.3.5)
      middleman-core (>= 3.3)
      tzinfo (>= 0.3.0)
    middleman-core (3.3.7)
      activesupport (~> 4.1.0)
      bundler (~> 1.1)
      erubis
      hooks (~> 0.3)
      i18n (~> 0.6.9)
      listen (>= 2.7.9, < 3.0)
      padrino-helpers (~> 0.12.3)
      rack (>= 1.4.5, < 2.0)
      rack-test (~> 0.6.2)
      thor (>= 0.15.2, < 2.0)
      tilt (~> 1.4.1, < 2.0)
    middleman-imageoptim (0.2.1)
      image_optim (~> 0.20.2)
      image_optim_pack (~> 0.2.1)
      middleman-core (>= 3.1)
    middleman-inliner (1.0.1)
    middleman-livereload (3.4.2)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-minify-html (3.4.0)
      htmlcompressor (~> 0.1.0)
      middleman-core (>= 3.2)
    middleman-sprockets (3.4.2)
      middleman-core (>= 3.3)
      sprockets (~> 2.12.1)
      sprockets-helpers (~> 1.1.0)
      sprockets-sass (~> 1.3.0)
    minitest (5.6.1)
    modular-scale (2.0.6)
      compass (>= 0.12.0)
    multi_json (1.11.0)
    padrino-helpers (0.12.5)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.12.5)
      tilt (~> 1.4.1)
    padrino-support (0.12.5)
      activesupport (>= 3.1)
    progress (3.1.0)
    rack (1.6.1)
    rack-livereload (0.3.15)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    sass (3.4.11)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-helpers (1.1.0)
      sprockets (~> 2.0)
    sprockets-sass (1.3.1)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    timers (4.0.1)
      hitimes
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uber (0.0.13)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)

PLATFORMS
  ruby

DEPENDENCIES
  color-schemer (= 0.2.8)
  compass (= 1.0.3)
  middleman (= 3.3.7)
  middleman-blog (= 3.6.0.beta.2)
  middleman-imageoptim (= 0.2.1)
  middleman-inliner (= 1.0.1)
  middleman-livereload (= 3.4.2)
  middleman-minify-html (= 3.4.0)
  modular-scale (= 2.0.6)
  sass (= 3.4.11)
  tzinfo-data
  wdm (~> 0.1.0)
```

**Comment by tdreyno** [comment]
@scottkellum Looks like `rb-fsevent` just updated. It's working a lot better for me in 10.10 now. Can you `bundle update` and see if this is resolved?

**Comment by scottkellum** [comment]
@tdreyno So… I ended up doing a fresh install of Yosemite and it solved the issue. thanks!
