### ISSUE TITLE
You're seeing this error because you use Rack::ShowExceptions.

### ISSUE THREAD

**Issue by JoeNoPhoto** [middleman/middleman#1536]
I'm trying to start the preview server for the first time . At the bottom of the Chrome error window when trying to access localhost:4567, I get the error from the title. I don't know if that's a symptom of a different problem or the cause, but here's all of the reproduction info I can think of. 

**versions**
rvm 1.26.11
ruby 2.2.1p85
gem 2.4.7
Middleman 3.3.12

**Steps to reproduce**
1. gem install middleman
2. middleman init test
3.cd test
4. middleman server
5. [In Chrome] localhost:4567

[**Terminal Error**:
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
== The Middleman is loading
== The Middleman is standing watch at http://Computer-MBP.local:4567/ (http://10.0.1.3:4567/)
== Inspect your site configuration at http://Computer-MBP.local:4567/__middleman
NoMethodError: undefined method `force_encoding' for nil:NilClass
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:289:in`ensure in binary'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:289:in `binary'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:279:in`extract_magic_comment'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:275:in `extract_encoding'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:191:in`precompiled'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/erb.rb:57:in `precompiled'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/erb.rb:104:in`precompiled'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:245:in `compile_template_method'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:240:in`compiled_method'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:169:in `evaluate'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in`render'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:303:in `render_individual_file'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:153:in`render_template'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.10/lib/active_support/notifications.rb:161:in`instrument'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/util.rb:41:in `instrument'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/application.rb:235:in`instrument'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:14:in `instrument'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:100:in`render'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:260:in `process_request'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:210:in`block in call!'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in `catch'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in`call!'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:195:in `call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb:66:in`block in call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb:50:in `each'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb:50:in`call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/head.rb:13:in`call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/lint.rb:49:in `_call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/lint.rb:37:in`call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/builder.rb:153:in `call'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in`service'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in`run'
    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'}

[**Chrome Error**
NoMethodError at /
undefined method `force_encoding' for nil:NilClass

Ruby    /Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in ensure in binary, line 289
Web GET localhost/

**Traceback** (innermost first)

/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in ensure in binary
      string.force_encoding(original_encoding)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in binary
      string.force_encoding(original_encoding)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in extract_magic_comment
      binary script do...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in extract_encoding
      extract_magic_comment(script) || script.encoding...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in precompiled
        template_encoding = extract_encoding(template)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/erb.rb: in precompiled
        source, offset = super...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/erb.rb: in precompiled
        source, offset = super...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in compile_template_method
      source, offset = precompiled(locals)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in compiled_method
        compile_template_method(locals_keys)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in evaluate
      method = compiled_method(locals.keys)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb: in render
      evaluate scope, locals || {}, &block...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb: in render_individual_file
          content = template.render(context, locs, &block)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb: in render_template
            content = render_individual_file(layout_path, locs, opts, context) { content }...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb: in block in render
          app.render_template(source_file, locs, opts, blocks)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.10/lib/active_support/notifications.rb: in instrument
          yield payload if block_given?...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/util.rb: in instrument
        ::ActiveSupport::Notifications.instrument(suffixed_name, payload, &block)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/application.rb: in instrument
    delegate :instrument, to: ::Middleman::Util...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb: in instrument
      delegate :logger, :instrument, to: :app...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb: in render
        instrument 'render.resource', path: relative_source, destination_path: destination_path  do...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb: in process_request
            output = resource.render do...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb: in block in call!
            process_request(env, req, res)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb: in catch
          catch(:halt) do...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb: in call!
          catch(:halt) do...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb: in call
          dup.call!(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb: in block in call
        return app.call(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb: in each
      @mapping.each do |host, location, match, app|...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb: in call
      @mapping.each do |host, location, match, app|...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/showexceptions.rb: in call
      @app.call(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/head.rb: in call
    status, headers, body = @app.call(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/lint.rb: in _call
      status, headers, @body = @app.call(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/lint.rb: in call
      dup._call(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/builder.rb: in call
      to_app.call(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/handler/webrick.rb: in service
        status, headers, body = @app.call(env)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb: in service
      si.service(req, res)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb: in run
          server.service(req, res)...
/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb: in block in start_thread
          block ? block.call(sock) : run(sock)...
**Request information**

**GET**
No GET data.
**POST**
No POST data.
**COOKIES**
No cookie data.
*_Rack ENV
Variable    Value
GATEWAY_INTERFACE  
CGI/1.1
HTTP_ACCEPT 
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/*;q=0.8
HTTP_ACCEPT_ENCODING  
gzip, deflate, sdch
HTTP_ACCEPT_LANGUAGE  
en-US,en;q=0.8
HTTP_CONNECTION 
keep-alive
HTTP_DNT  
1
HTTP_HOST  
localhost:4567
HTTP_USER_AGENT 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2424.0 Safari/537.36
HTTP_VERSION  
HTTP/1.1
PATH_INFO  
/
QUERY_STRING  
REMOTE_ADDR 
::1
REMOTE_HOST 
::1
REQUEST_METHOD  
GET
REQUEST_PATH  
/
REQUEST_URI 
http://localhost:4567/
SCRIPT_NAME 
SERVER_NAME 
localhost
SERVER_PORT 
4567
SERVER_PROTOCOL 
HTTP/1.1
SERVER_SOFTWARE 
WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26) OpenSSL/1.0.2a
rack.errors 
# <Rack::Lint::ErrorWrapper:0x007f88660f3070 @error=#<IO:<STDERR>>>

rack.hijack 
# Proc:0x007f88660f3458@/Users/myComp/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/lint.rb:525

rack.hijack?  
true
rack.hijack_io  
nil
rack.input  
# <Rack::Lint::InputWrapper:0x007f88660f3098 @input=#<StringIO:0x007f8866108f38>>

rack.multiprocess  
false
rack.multithread  
true
rack.request.cookie_hash  
{}
rack.request.query_hash 
{}
rack.request.query_string  
rack.run_once  
false
rack.url_scheme 
http
rack.version  
[1, 3]
You're seeing this error because you use Rack::ShowExceptions.]

I don't know if this is relevant to my issues but...
*\* $ bundle --clean --force results:**
Removing foundation (1.0.4)
Removing jekyll (2.5.3)
Removing rb-fsevent (0.9.4)
Removing sass (3.4.13)

**$ bundle install results:**
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.10
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.4
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using coffee-script 2.4.1
Using multi_json 1.11.0
Using sass 3.4.14
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.5
Using ffi 1.9.8
Using rb-inotify 0.9.5
Using compass 1.0.3
Using eventmachine 1.0.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using erubis 2.7.0
Using tilt 1.4.1
Using haml 4.0.6
Using hike 1.2.3
Using uber 0.0.13
Using hooks 0.4.0
Using kramdown 1.7.0
Using listen 2.10.0
Using bundler 1.10.3
Using padrino-support 0.12.5
Using padrino-helpers 0.12.5
Using rack 1.6.1
Using rack-test 0.6.3
Using thor 0.19.1
Using middleman-core 3.3.12
Using sprockets 2.12.3
Using sprockets-helpers 1.1.0
Using sprockets-sass 1.3.1
Using middleman-sprockets 3.4.2
Using uglifier 2.7.1
Using middleman 3.3.12
Using rack-livereload 0.3.15
Using middleman-livereload 3.1.1
Bundle complete! 4 Gemfile dependencies, 47 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**$ 'bundle exec middleman' produces:
== The Middleman is loading
== The Middleman is standing watch at http://Blackstar-MBP.local:4567/ (http://10.0.1.3:4567/)
== Inspect your site configuration at http://Blackstar-MBP.local:4567/__middleman

So the json warning goes away with that, but the instant I enter the L in localhost:4567 into Chrome, the NoMethodError appears again in console. 

I don't know exactly what I'm missing, or what step I'm not doing properly.

**Comment by Arcovion** [comment]
Was fixed in #1506, for now you can use this in your `Gemfile` until the next release:
```ruby
gem 'middleman', github: 'middleman', branch: 'v3-stable'
```

**Comment by JoeNoPhoto** [comment]
@Arcovion, 

I'm still receiving error: 

**test $ bundle clean --force**
Removing foundation (1.0.4)
Removing jekyll (2.5.3)
Removing rb-fsevent (0.9.4)
Removing sass (3.4.13)

**test $ bundle install**
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.10
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.4
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using coffee-script 2.4.1
Using multi_json 1.11.0
Using sass 3.4.14
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.5
Using ffi 1.9.8
Using rb-inotify 0.9.5
Using compass 1.0.3
Using eventmachine 1.0.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using erubis 2.7.0
Using tilt 1.4.1
Using haml 4.0.6
Using hike 1.2.3
Using uber 0.0.13
Using hooks 0.4.0
Using kramdown 1.7.0
Using listen 2.10.0
Using bundler 1.10.3
Using padrino-support 0.12.5
Using padrino-helpers 0.12.5
Using rack 1.6.1
Using rack-test 0.6.3
Using thor 0.19.1
Using middleman-core 3.4.0 from git://github.com/middleman/middleman.git (at v3-stable)
Using sprockets 2.12.3
Using sprockets-helpers 1.1.0
Using sprockets-sass 1.3.1
Using middleman-sprockets 3.4.2
Using uglifier 2.7.1
Using middleman 3.4.0 from git://github.com/middleman/middleman.git (at v3-stable)
Using rack-livereload 0.3.15
Using middleman-livereload 3.1.1
Bundle complete! 4 Gemfile dependencies, 47 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
test $ bundle exec middleman
== The Middleman is loading
== The Middleman is standing watch at http://Blackstar-MBP.local:4567/ (http://10.0.1.3:4567/)
== Inspect your site configuration at http://Blackstar-MBP.local:4567/__middleman

**Then after reloading localhost:4567, the teminal message:**
NoMethodError: undefined method `force_encoding' for nil:NilClass
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:289:in `ensure in binary'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:289:in `binary'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:279:in `extract_magic_comment'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:275:in `extract_encoding'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:191:in `precompiled'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/erb.rb:57:in `precompiled'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/erb.rb:104:in `precompiled'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:245:in `compile_template_method'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:240:in `compiled_method'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:169:in `evaluate'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/core_extensions/rendering.rb:303:in `render_individual_file'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/core_extensions/rendering.rb:153:in `render_template'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.10/lib/active_support/notifications.rb:161:in `instrument'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/util.rb:41:in `instrument'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/application.rb:241:in `instrument'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/sitemap/resource.rb:14:in `instrument'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/sitemap/resource.rb:100:in `render'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/core_extensions/request.rb:260:in `process_request'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/core_extensions/request.rb:210:in `block in call!'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/core_extensions/request.rb:209:in `catch'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/core_extensions/request.rb:209:in `call!'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/middleman-a38a20322f38/middleman-core/lib/middleman-core/core_extensions/request.rb:195:in `call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb:66:in `block in call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb:50:in `each'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/urlmap.rb:50:in `call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/lint.rb:49:in `_call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/lint.rb:37:in `call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/builder.rb:153:in `call'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/JoeNoPhoto/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**And I get the same error as before on the Chrome page**

**Comment by tdreyno** [comment]
@JoeNoPhoto Can you post the result of `pwd`

**Comment by JoeNoPhoto** [comment]
@tdreyno:
pwd of the test project?
 /Users/JoeNoPhoto/Projects/test

**Comment by tdreyno** [comment]
Hmm, can you try Ruby `2.2.2`?

**Comment by JoeNoPhoto** [comment]
@tdreyno, I tried 2.2.2 as well. Here's my exact steps, just in case I'm missing something somewhere. 

After the ruby 2.2.2 update:

**Projects $ ruby -v**
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

Projects $ gem install middleman
Fetching: middleman-core-3.3.12.gem (100%)
Successfully installed middleman-core-3.3.12
Fetching: middleman-3.3.12.gem (100%)
Successfully installed middleman-3.3.12
Parsing documentation for middleman-core-3.3.12
Parsing documentation for middleman-3.3.12
Done installing documentation for middleman-core, middleman after 1 seconds
2 gems installed

**Projects $ middleman init test**
      create  test/Gemfile
         run  bundle install from "."
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.10
Using bundler 1.10.3
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.4
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using coffee-script 2.4.1
Using multi_json 1.11.0
Using sass 3.4.14
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.5
Using ffi 1.9.8
Using rb-inotify 0.9.5
Using compass 1.0.3
Using eventmachine 1.0.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using erubis 2.7.0
Using tilt 1.4.1
Using haml 4.0.6
Using hike 1.2.3
Using uber 0.0.13
Using hooks 0.4.0
Using kramdown 1.7.0
Using listen 2.10.0
Using padrino-support 0.12.5
Using padrino-helpers 0.12.5
Using rack 1.6.1
Using rack-test 0.6.3
Using thor 0.19.1
Using middleman-core 3.3.12
Using sprockets 2.12.3
Using sprockets-helpers 1.1.0
Using sprockets-sass 1.3.1
Using middleman-sprockets 3.4.2
Using uglifier 2.7.1
Using middleman 3.3.12
Using rack-livereload 0.3.15
Using middleman-livereload 3.1.1
Bundle complete! 4 Gemfile dependencies, 47 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
      create  test/.gitignore
      create  test/config.rb
      create  test/source/index.html.erb
      create  test/source/layouts/layout.erb
      create  test/source/stylesheets
      create  test/source/stylesheets/all.css
      create  test/source/stylesheets/normalize.css
      create  test/source/javascripts
      create  test/source/javascripts/all.js
      create  test/source/images
      create  test/source/images/background.png
      create  test/source/images/middleman.png

**I then replaced 'gem "middleman", "~>3.3.12"' in my gemfile with:**
**gem 'middleman', github: 'middleman', branch: 'v3-stable'**

**Projects $ cd test**

**test $ bundle clean --force**
Removing middleman (a38a20322f38)

**test $ bundle install**
Fetching git://github.com/middleman/middleman.git
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.10
Using bundler 1.10.3
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.4
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using coffee-script 2.4.1
Using multi_json 1.11.0
Using sass 3.4.14
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.5
Using ffi 1.9.8
Using rb-inotify 0.9.5
Using compass 1.0.3
Using eventmachine 1.0.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using erubis 2.7.0
Using tilt 1.4.1
Using haml 4.0.6
Using hike 1.2.3
Using uber 0.0.13
Using hooks 0.4.0
Using kramdown 1.7.0
Using listen 2.10.0
Using padrino-support 0.12.5
Using padrino-helpers 0.12.5
Using rack 1.6.1
Using rack-test 0.6.3
Using thor 0.19.1
Using middleman-core 3.4.0 (was 3.3.12) from git://github.com/middleman/middleman.git (at v3-stable)
Using sprockets 2.12.3
Using sprockets-helpers 1.1.0
Using sprockets-sass 1.3.1
Using middleman-sprockets 3.4.2
Using uglifier 2.7.1
Using middleman 3.4.0 (was 3.3.12) from git://github.com/middleman/middleman.git (at v3-stable)
Using rack-livereload 0.3.15
Using middleman-livereload 3.1.1
Bundle complete! 4 Gemfile dependencies, 47 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**test $ bundle exec middleman**
== The Middleman is loading
== The Middleman is standing watch at http://Blackstar-MBP.local:4567/ (http://10.0.1.3:4567/)
== Inspect your site configuration at http://Blackstar-MBP.local:4567/__middleman
**Try localhost:4567 in Chrome and receive the same error in terminal and in the browser as above.**

**Comment by afomi** [comment]
This issue has similar symptoms to https://github.com/rails/rails/issues/18660.

When I `pwd` my Middleman project directory that generates this error, the directory is mixed-case (and symlink'd).
Moving the project to a down-cased directory solved this issue for me.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
