### ISSUE TITLE
Haml::TemplateEngine throwing errors

### ISSUE THREAD

**Issue by meowsus** [middleman/middleman#2113]
## Expected behavior and actual behavior

I should be able to use the newest version of Haml, however Haml v5.0+ throws errors:

```
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
```

## Steps to reproduce the problem (from a clean middleman installation)

In terminal (to convert views)
```
cd path/to/project
gem install html2haml
find . -name \*.erb -print | sed 'p;s/.erb$/.haml/' | xargs -n2 html2haml
```

In gemfile:
```rb
gem 'haml', '>= 5.0'
```

In terminal
```
bundle update
bundle exec middleman
```

Browsing around you will see the error.

## Additional information

- Ruby version: 2.4.1
- Middleman version: 4.2.1
- OS version: OS X Sierra

**Comment by meowsus** [comment]
This really isn't a concern of Middleman, since Haml is not a dependency of this project.

To get around these errors put the following in the `config.rb` file:

```rb
Haml::TempleEngine.disable_option_validator!
```

**Comment by monfresh** [comment]
Haml has been a dependency since at least 4 years ago. You can see it listed as a dependency here: https://github.com/middleman/middleman/blob/master/middleman/middleman.gemspec#L24

Should this issue be re-opened? After updating to the latest Middleman (I tried both 4.2.1 and 4.3.0.rc.1), and I see a bunch of the following errors when I run `middleman build`:

```
Haml::TempleEngine: Option :lang is invalid
Haml::TempleEngine: Option :locale is invalid
```

**Comment by dzienisz** [comment]
I have this same issue

**Comment by nburns** [comment]
Is this form something Haml is doing or is middleman not using haml correctly?

**Comment by davideghz** [comment]
+1 same issue here `Haml::TempleEngine: Option :locale is invalid`

**Comment by tdreyno** [comment]
This was resolved in v4.3.2: https://github.com/middleman/middleman/blob/4.x/CHANGELOG.md#432

**Comment by davideghz** [comment]
@tdreyno I'm on 4.3.3 and still got that warnings

**Comment by ChristianPeters** [comment]
@tdreyno I can confirm: This is still a problem with `4.3.3`.

With middleman 4.2.1 and Haml 5.0.4 I got all those warnings:

```
Haml::TempleEngine: Option :locale is invalid
Haml::TempleEngine: Option :ugly is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
…
```
After updating middleman to `4.3.3` and removing the ugly option from `config.rb` the one about `locale` stays:

```
Haml::TempleEngine: Option :locale is invalid
Haml::TempleEngine: Option :locale is invalid
Haml::TempleEngine: Option :locale is invalid
…
```

**Comment by tdreyno** [comment]
Does the above solution, `Haml::TempleEngine.disable_option_validator!`, not work?

**Comment by ChristianPeters** [comment]
Well yes, I can suppress the warnings with that. Doesn't feel right though. ;)

**Comment by tdreyno** [comment]
As the original responder mentioned, I don't think we're interested in tracking along with the internal API changes of the various templating engine we support. This specific case isn't handled because Haml had a major rev some time back and we had to support 2 incompatible version. We can't change the variable in use because it would break users on the old Haml. In this specific case, it's just a warning and one that is kind of saying something useful. `locale` is a Middleman concept that Haml doesn't understand. I'm okay allowing it to continue not understanding as long as it's not an error.

I'm also hesitant to blindly silence all warnings. In this case, I understand the root cause and can ignore it, but in others it may be useful information.

**Comment by pomartel** [comment]
For those updating to HAML 6, the workaround to silence the warnings is now: `Haml::Engine.disable_option_validator!`

And for backward compatibility with escaping HTML, I also added this to my `config.rb` file:

```
Haml::Template.options[:escape_html] = false
Haml::Template.options[:escape_attrs] = false
```
