### ISSUE TITLE
scss file gives Internal Server Error SyntaxError: Unexpected token, in JSON at position 3

### ISSUE THREAD

**Issue by snitko** [middleman/middleman#2242]
Just created a fresh website with middleman. Renamed `stylesheets/site.css` into `stylesheets/site.css.scss` and when I navigate my browser to `http://localhost:4567/stylesheets/site.css` I get an error page with the following message:

```
Internal Server Error
SyntaxError: Unexpected token , in JSON at position 3
```
If I renamed the file back to `stylesheets/site.css`, then it actually loads the css file. Please advise. It seems it's not very simple to just start using scss with Middleman v4 although the documentation says it comes built in. The documentation also doesn't provide any further explanation about scss.

## Additional information
- Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- Middleman version: 4.3.0
- OS version: Ubuntu Linux 18.04

**Comment by tysongach** [comment]
I’m seeing the same thing, and many of my existing Middleman sites have failed to compile their Sass.

## Steps to reproduce the problem

- Run `middleman init`
- Run `middleman server`
- View the site in a browser
- CSS is not functioning; console error:
    - `GET http://localhost:4567/stylesheets/site.css net::ERR_ABORTED 500 (Internal Server Error)`

On existing sites, I'm also seeing the Sass error:

```
SassC::SyntaxError: Error: File to import not found or unreadable: bourbon.
```

**Comment by tdreyno** [comment]
@snitko Revert to 4.2.1 for now. Looks like our upgrade to sassc messed something up.

**Comment by tdreyno** [comment]
@tysongach fixed in branch. Can you re-test?

**Comment by tysongach** [comment]
@tdreyno Quick test pulling that branch doesn’t appear to fix the issue. I’m a bit limited on time this afternoon.

Here are two open repos where the upgrade broke our Sass and where this can be tested:

- https://github.com/thoughtbot/apprentice.thoughtbot.com
- https://github.com/thoughtbot/presskit

**Comment by tdreyno** [comment]
Looks to be an issue in autoprefixer... interesting.

**Comment by tdreyno** [comment]
Derp, PR just sitting there waiting. 🤦‍♂️ 

https://github.com/middleman/middleman-autoprefixer/pull/34

**Comment by tysongach** [comment]
Back to normal. Thanks @tdreyno!
