### ISSUE TITLE
TypeError: Cannot read property 'version' of undefined (problems with style.css

### ISSUE THREAD

**Issue by fguillen** [middleman/middleman#2480]
## Expected behavior and actual behavior

Not errors in console.

style.css file built properly

## Steps to reproduce the problem (from a clean middleman installation)

I am using the version on github. But the problem was already starting with the last stable version in rubygems

With an empty project:

```
> bundle exec middleman build  
      create  build/stylesheets/site.css
      create  build/images/.keep
      create  build/javascripts/site.js
      create  build/index.html
Project built successfully.
```

```
== Request: /
== Finishing Request: index.html (0.04s)
== Request: /stylesheets/site.css
== Finishing Request: stylesheets/site.css (0.01s)
== Request: /javascripts/site.js
DEPRECATION WARNING: autoprefixer-rails was deprected. Migration guide:
https://github.com/ai/autoprefixer-rails/wiki/Deprecated (called from process at /Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/autoprefixer-rails-9.8.6.5/lib/autoprefixer-rails/processor.rb:36)
== Finishing Request: javascripts/site.js (0.0s)
TypeError: Cannot read property 'version' of undefined
[2021-06-14 19:16:52] ERROR ExecJS::ProgramError: TypeError: Cannot read property 'version' of undefined
	eval (eval at <anonymous> ((execjs):1:213), <anonymous>:1:10)
	(execjs):1:213
	(execjs):19:14
	(execjs):1:40
	Object.<anonymous> ((execjs):1:58)
	Module._compile (node:internal/modules/cjs/loader:1092:14)
	Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
	Module.load (node:internal/modules/cjs/loader:972:32)
	Function.Module._load (node:internal/modules/cjs/loader:813:14)
	Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:39:in `exec'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:21:in `eval'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/runtime.rb:64:in `eval'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/autoprefixer-rails-9.8.6.5/lib/autoprefixer-rails/processor.rb:170:in `runtime'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/autoprefixer-rails-9.8.6.5/lib/autoprefixer-rails/processor.rb:53:in `process'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:83:in `prefix'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:74:in `process'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:60:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
== Request: /stylesheets/site.css
== Finishing Request: stylesheets/site.css (0.01s)
TypeError: Cannot read property 'version' of undefined
[2021-06-14 19:17:40] ERROR ExecJS::ProgramError: TypeError: Cannot read property 'version' of undefined
	eval (eval at <anonymous> ((execjs):1:213), <anonymous>:1:10)
	(execjs):1:213
	(execjs):19:14
	(execjs):1:40
	Object.<anonymous> ((execjs):1:58)
	Module._compile (node:internal/modules/cjs/loader:1092:14)
	Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
	Module.load (node:internal/modules/cjs/loader:972:32)
	Function.Module._load (node:internal/modules/cjs/loader:813:14)
	Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:39:in `exec'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:21:in `eval'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/runtime.rb:64:in `eval'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/autoprefixer-rails-9.8.6.5/lib/autoprefixer-rails/processor.rb:170:in `runtime'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/autoprefixer-rails-9.8.6.5/lib/autoprefixer-rails/processor.rb:53:in `process'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:83:in `prefix'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:74:in `process'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:60:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
	/Users/fernando.guillen/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
```

The last error is when trying to load the style.css file (see [image](https://pasteboard.co/K6BaJQg.png))

## Additional information

- Ruby version: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin19]
- Middleman version: Middleman 5.0.0.rc.2
- OS version: Catalina 10.15.5

**Comment by fguillen** [comment]
When I use

    bundle exec middleman build`

It woks properly

**Comment by tdreyno** [comment]
Sorry, what is the difference between the two builds?

**Comment by noraj** [comment]
Seems related to #2463

**Comment by noraj** [comment]
Fixed by:

```diff
-gem 'middleman-autoprefixer', '~> 2.10'
+gem 'middleman-autoprefixer', '~> 3.0'
```

**Comment by Mayurifag** [comment]
I can confirm @noraj solution — I forgot to change fixed autoprefixer version after middleman update

**Comment by DannyBen** [comment]
Why is this closed?
The issue still exists (in the published gem at least).

I suggest that the `middleman init` function brings a `Gemfile` that is not requesting specific versions:

```ruby
gem 'middleman'
gem 'middleman-autoprefixer'
```

After updating the `Gemfile` to this, and running `bundle update`, it works.

**Comment by jagthedrummer** [comment]
Just ran into this in a brand new project.

**Comment by grtcdr** [comment]
@jagthedrummer Yeah, me too, I installed middleman yesterday.

The issue was fixed by updating middleman-autoprefixer to its latest version, perhaps the issue should be reopened until it is actually addressed.

**Comment by tdreyno** [comment]
The source code for new project generation is in this repo: https://github.com/middleman/middleman-templates-default

**Comment by gbirchmeier** [comment]
Still an active problem in the currently-published gem.  Kind of a big speedbump for noobs like me to the project.

**Comment by asecondwill** [comment]
I hit this trying to install a new middleman.  defo still broken.  please reopen @tdreyno
